// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    'glossary',
    {
      type: 'category',
      label: 'ROS 2 Robotic Nervous System',
      items: [
        'ros2-nervous-system/index',
        'ros2-nervous-system/introduction-to-ros2',
        'ros2-nervous-system/ros2-communication',
        'ros2-nervous-system/urdf-modeling'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Digital Twin Simulation',
      items: [
        'digital-twin-simulation/index',
        'digital-twin-simulation/digital-twins-for-physical-ai',
        'digital-twin-simulation/physics-simulation-with-gazebo',
        'digital-twin-simulation/high-fidelity-interaction-sensors'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'AI-Robot Brain',
      items: [
        'ai-robot-brain-isaac/index',
        'ai-robot-brain-isaac/nvidia-isaac-sim-synthetic-data',
        'ai-robot-brain-isaac/isaac-ros-accelerated-perception',
        'ai-robot-brain-isaac/autonomous-navigation-nav2'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Vision-Language-Action Integration',
      items: [
        'vla-integration/index',
        'vla-integration/voice-to-action-interfaces',
        'vla-integration/cognitive-planning-vision-language',
        'vla-integration/autonomous-humanoid-capstone'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
